# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import fetch_pb2 as fetch__pb2


class FetchStub(object):
  """The Fetch service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Fetch_CheckOut = channel.unary_unary(
        '/Fetch/Fetch_CheckOut',
        request_serializer=fetch__pb2.Fetch_CheckOutRequest.SerializeToString,
        response_deserializer=fetch__pb2.Fetch_CheckOutReply.FromString,
        )
    self.Fetch_CheckIn = channel.unary_unary(
        '/Fetch/Fetch_CheckIn',
        request_serializer=fetch__pb2.Fetch_CheckInRequest.SerializeToString,
        response_deserializer=fetch__pb2.Fetch_CheckInReply.FromString,
        )


class FetchServicer(object):
  """The Fetch service definition.
  """

  def Fetch_CheckOut(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Fetch_CheckIn(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FetchServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Fetch_CheckOut': grpc.unary_unary_rpc_method_handler(
          servicer.Fetch_CheckOut,
          request_deserializer=fetch__pb2.Fetch_CheckOutRequest.FromString,
          response_serializer=fetch__pb2.Fetch_CheckOutReply.SerializeToString,
      ),
      'Fetch_CheckIn': grpc.unary_unary_rpc_method_handler(
          servicer.Fetch_CheckIn,
          request_deserializer=fetch__pb2.Fetch_CheckInRequest.FromString,
          response_serializer=fetch__pb2.Fetch_CheckInReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Fetch', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
