# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fetch_pb2 as fetch__pb2


class FetchStub(object):
    """The Fetch service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Fetch_CheckOut = channel.unary_unary(
                '/Fetch/Fetch_CheckOut',
                request_serializer=fetch__pb2.Fetch_CheckOutRequest.SerializeToString,
                response_deserializer=fetch__pb2.Fetch_CheckOutReply.FromString,
                )
        self.Fetch_CheckIn = channel.unary_unary(
                '/Fetch/Fetch_CheckIn',
                request_serializer=fetch__pb2.Fetch_CheckInRequest.SerializeToString,
                response_deserializer=fetch__pb2.Fetch_CheckInReply.FromString,
                )


class FetchServicer(object):
    """The Fetch service definition.
    """

    def Fetch_CheckOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fetch_CheckIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FetchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Fetch_CheckOut': grpc.unary_unary_rpc_method_handler(
                    servicer.Fetch_CheckOut,
                    request_deserializer=fetch__pb2.Fetch_CheckOutRequest.FromString,
                    response_serializer=fetch__pb2.Fetch_CheckOutReply.SerializeToString,
            ),
            'Fetch_CheckIn': grpc.unary_unary_rpc_method_handler(
                    servicer.Fetch_CheckIn,
                    request_deserializer=fetch__pb2.Fetch_CheckInRequest.FromString,
                    response_serializer=fetch__pb2.Fetch_CheckInReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Fetch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Fetch(object):
    """The Fetch service definition.
    """

    @staticmethod
    def Fetch_CheckOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Fetch/Fetch_CheckOut',
            fetch__pb2.Fetch_CheckOutRequest.SerializeToString,
            fetch__pb2.Fetch_CheckOutReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Fetch_CheckIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Fetch/Fetch_CheckIn',
            fetch__pb2.Fetch_CheckInRequest.SerializeToString,
            fetch__pb2.Fetch_CheckInReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
