# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kinova.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kinova.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ckinova.proto\"4\n\x0f\x43heckOutRequest\x12\x0e\n\x06kit_ID\x18\x01 \x01(\x05\x12\x11\n\titem_list\x18\x02 \x03(\x05\"3\n\x0e\x43heckInRequest\x12\x0e\n\x06kit_ID\x18\x01 \x01(\x05\x12\x11\n\titem_list\x18\x02 \x03(\x05\"#\n\rCheckOutReply\x12\x12\n\nitem_ready\x18\x01 \x01(\x08\"%\n\x0c\x43heckInReply\x12\x15\n\ritem_returned\x18\x01 \x01(\x08\x32\x65\n\x06Kinova\x12.\n\x08\x43heckOut\x12\x10.CheckOutRequest\x1a\x0e.CheckOutReply\"\x00\x12+\n\x07\x43heckIn\x12\x0f.CheckInRequest\x1a\r.CheckInReply\"\x00\x62\x06proto3'
)




_CHECKOUTREQUEST = _descriptor.Descriptor(
  name='CheckOutRequest',
  full_name='CheckOutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kit_ID', full_name='CheckOutRequest.kit_ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item_list', full_name='CheckOutRequest.item_list', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=68,
)


_CHECKINREQUEST = _descriptor.Descriptor(
  name='CheckInRequest',
  full_name='CheckInRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kit_ID', full_name='CheckInRequest.kit_ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item_list', full_name='CheckInRequest.item_list', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=121,
)


_CHECKOUTREPLY = _descriptor.Descriptor(
  name='CheckOutReply',
  full_name='CheckOutReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_ready', full_name='CheckOutReply.item_ready', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=158,
)


_CHECKINREPLY = _descriptor.Descriptor(
  name='CheckInReply',
  full_name='CheckInReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_returned', full_name='CheckInReply.item_returned', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=197,
)

DESCRIPTOR.message_types_by_name['CheckOutRequest'] = _CHECKOUTREQUEST
DESCRIPTOR.message_types_by_name['CheckInRequest'] = _CHECKINREQUEST
DESCRIPTOR.message_types_by_name['CheckOutReply'] = _CHECKOUTREPLY
DESCRIPTOR.message_types_by_name['CheckInReply'] = _CHECKINREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CheckOutRequest = _reflection.GeneratedProtocolMessageType('CheckOutRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKOUTREQUEST,
  '__module__' : 'kinova_pb2'
  # @@protoc_insertion_point(class_scope:CheckOutRequest)
  })
_sym_db.RegisterMessage(CheckOutRequest)

CheckInRequest = _reflection.GeneratedProtocolMessageType('CheckInRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKINREQUEST,
  '__module__' : 'kinova_pb2'
  # @@protoc_insertion_point(class_scope:CheckInRequest)
  })
_sym_db.RegisterMessage(CheckInRequest)

CheckOutReply = _reflection.GeneratedProtocolMessageType('CheckOutReply', (_message.Message,), {
  'DESCRIPTOR' : _CHECKOUTREPLY,
  '__module__' : 'kinova_pb2'
  # @@protoc_insertion_point(class_scope:CheckOutReply)
  })
_sym_db.RegisterMessage(CheckOutReply)

CheckInReply = _reflection.GeneratedProtocolMessageType('CheckInReply', (_message.Message,), {
  'DESCRIPTOR' : _CHECKINREPLY,
  '__module__' : 'kinova_pb2'
  # @@protoc_insertion_point(class_scope:CheckInReply)
  })
_sym_db.RegisterMessage(CheckInReply)



_KINOVA = _descriptor.ServiceDescriptor(
  name='Kinova',
  full_name='Kinova',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=199,
  serialized_end=300,
  methods=[
  _descriptor.MethodDescriptor(
    name='CheckOut',
    full_name='Kinova.CheckOut',
    index=0,
    containing_service=None,
    input_type=_CHECKOUTREQUEST,
    output_type=_CHECKOUTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckIn',
    full_name='Kinova.CheckIn',
    index=1,
    containing_service=None,
    input_type=_CHECKINREQUEST,
    output_type=_CHECKINREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_KINOVA)

DESCRIPTOR.services_by_name['Kinova'] = _KINOVA

# @@protoc_insertion_point(module_scope)
