# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kinova_pb2 as kinova__pb2


class KinovaStub(object):
    """The Kinova service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Kinova_CheckOut = channel.unary_unary(
                '/Kinova/Kinova_CheckOut',
                request_serializer=kinova__pb2.Kinova_CheckOutRequest.SerializeToString,
                response_deserializer=kinova__pb2.Kinova_CheckOutReply.FromString,
                )
        self.Kinova_CheckIn = channel.unary_unary(
                '/Kinova/Kinova_CheckIn',
                request_serializer=kinova__pb2.Kinova_CheckInRequest.SerializeToString,
                response_deserializer=kinova__pb2.Kinova_CheckInReply.FromString,
                )


class KinovaServicer(object):
    """The Kinova service definition.
    """

    def Kinova_CheckOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kinova_CheckIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KinovaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Kinova_CheckOut': grpc.unary_unary_rpc_method_handler(
                    servicer.Kinova_CheckOut,
                    request_deserializer=kinova__pb2.Kinova_CheckOutRequest.FromString,
                    response_serializer=kinova__pb2.Kinova_CheckOutReply.SerializeToString,
            ),
            'Kinova_CheckIn': grpc.unary_unary_rpc_method_handler(
                    servicer.Kinova_CheckIn,
                    request_deserializer=kinova__pb2.Kinova_CheckInRequest.FromString,
                    response_serializer=kinova__pb2.Kinova_CheckInReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Kinova', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Kinova(object):
    """The Kinova service definition.
    """

    @staticmethod
    def Kinova_CheckOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Kinova/Kinova_CheckOut',
            kinova__pb2.Kinova_CheckOutRequest.SerializeToString,
            kinova__pb2.Kinova_CheckOutReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Kinova_CheckIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Kinova/Kinova_CheckIn',
            kinova__pb2.Kinova_CheckInRequest.SerializeToString,
            kinova__pb2.Kinova_CheckInReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
